## Fashion MNIST Classification problem
----

### Importing Dataset 

In [1]:
from tensorflow.keras.datasets import fashion_mnist

### Spliting data into training and testing

In [2]:
(train_image , train_label) , (test_image , test_label) = fashion_mnist.load_data()

In [3]:
train_image.shape , test_image.shape

((60000, 28, 28), (10000, 28, 28))

In [4]:
train_label.size , test_label.size

(60000, 10000)

In [5]:
train_image[0].max()

255

In [6]:
train_image.max()

255

In [7]:
train_image.min()

0

### Preprocessing of data
#### 1-  Normalizing data

In [8]:
train_image = train_image / 255
test_image  = test_image  / 255

In [9]:
train_image.max()

1.0

In [10]:
test_image.min()

0.0

### Now for labels
#### to_categorical()

In [11]:
from tensorflow.keras.utils import to_categorical

In [12]:
train_label , test_label

(array([9, 0, 0, ..., 3, 0, 5], dtype=uint8),
 array([9, 2, 1, ..., 8, 1, 5], dtype=uint8))

In [13]:
train_label = to_categorical(train_label)
test_label  = to_categorical(test_label) 

In [14]:
train_label , test_label

(array([[0., 0., 0., ..., 0., 0., 1.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 1., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32))

---------

In [15]:
# import numpy as np

In [16]:
# np.ravel(test_image).size

784

### Building ANN model

In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten , Dense
from tensorflow.keras.optimizers import Adam

In [20]:
model = Sequential()

In [25]:
model.add(Flatten(input_shape = (28,28) ))
model.add(Dense(128, activation = 'relu'))
model.add(Dense(10, activation = 'softmax'))

In [26]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 32)                25120     
_________________________________________________________________
dense_1 (Dense)              (None, 10)                330       
_________________________________________________________________
flatten_1 (Flatten)          (None, 10)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 128)               1408      
_________________________________________________________________
dense_3 (Dense)              (None, 10)                1290      
Total params: 25,450
Trainable params: 25,450
Non-trainable params: 0
____________________________________________________

In [27]:
model.compile(optimizer=Adam(0.01),
              loss='categorical_crossentropy',
             metrics = ['accuracy'])

In [28]:
model.fit(train_image , train_label, epochs=15)

Train on 60000 samples
Epoch 1/15
60000/60000 [==============================] - 4s 75us/sample - loss: 0.4390 - accuracy: 0.8600
Epoch 2/15
60000/60000 [==============================] - 4s 68us/sample - loss: 0.4176 - accuracy: 0.8608
Epoch 3/15
60000/60000 [==============================] - 4s 70us/sample - loss: 0.4135 - accuracy: 0.8603
Epoch 4/15
60000/60000 [==============================] - 4s 67us/sample - loss: 0.4110 - accuracy: 0.8626
Epoch 5/15
60000/60000 [==============================] - 4s 69us/sample - loss: 0.4099 - accuracy: 0.8634
Epoch 6/15
60000/60000 [==============================] - 4s 68us/sample - loss: 0.4178 - accuracy: 0.8611
Epoch 7/15
60000/60000 [==============================] - 4s 71us/sample - loss: 0.4123 - accuracy: 0.8612
Epoch 8/15
60000/60000 [==============================] - 4s 71us/sample - loss: 0.4106 - accuracy: 0.8616
Epoch 9/15
60000/60000 [==============================] - 5s 77us/sample - loss: 0.4036 - accuracy: 0.8654
Epoch 10/15
60